### ISSUE TITLE
import key_config as keys

### ISSUE THREAD

**Issue by tsankar85** [aniketwattamwar/AWS-Flask#1]
Hi , 

import key_config as keys  is throwing an error.  I don't find a python package which has key_config. Is there any help on this ?

Thanks
Sankar

**Comment by aniketwattamwar** [comment]
Hi,

The key_config is a custom python file that I am importing, its not a library
You can mention the AWS keys directly in your main python file and it should work.

You can refer to my youtube video I have mentioned it: https://www.youtube.com/watch?v=EvHltGpbSqo&list=PL_drzcX_ki77Y18tcSV36j9kwRTekwTRA

Thanks
**Aniket**
